apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-container
        image: binubims/django-site:v1.0
        ports:
        - containerPort: 8080

        env:
        - name: PIPELINE
          value: "production"
        - name: SECRET_KEY
          value: "your_secret_key"
        - name: DB_NAME
          value: "."
        - name: DB_USER_NM
          value: "."
        - name: DB_USER_PW
          value: "."
        - name: DB_IP
          value: "0.0.0.0"
        - name: DB_PORT
          value: "5432"