name: CI/CD Pipeline

on:
  [workflow_dispatch]
  # push:
  #   branches:
  #     - main  # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: docker build ./dockerizing_django/titanic -t ${{ secrets.DOCKER_HUB_USERNAME }}/django-eks:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/django-eks:latest

  # deploy-to-eks:
  #   runs-on: ubuntu-latest
  #   needs: build-and-push  # Ensure this job runs after the build-and-push job

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v3
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: your-aws-region  # Replace with your AWS region

  #     - name: Install kubectl
  #       run: |
  #         curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  #         sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

  #     - name: Update kubeconfig
  #       run: aws eks --region your-aws-region update-kubeconfig --name your-cluster-name  # Replace with your EKS cluster name

  #     - name: Deploy to EKS
  #       run: |
  #         kubectl set image deployment/your-deployment-name your-container-name=${{ secrets.DOCKER_HUB_USERNAME }}/your-repo-name:latest